networks:
  elastic:
    name: elastic
    external: true


services:

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
  #   ports:
  #     - "9200:9200"
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.6.0
  #   ports:
  #     - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    volumes:
      - ./logstash/pipelines:/usr/share/logstash/pipeline/
    networks:
      - elastic